version: '2'
services:
    timetrackr-app:
        image: timetrackr
        external_links:
            - timetrackr-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/timetrackr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timetrackr-mysql:
        extends:
            file: mysql.yml
            service: timetrackr-mysql
